import type { Metadata } from "next";
import { Roboto } from "next/font/google";
import "./globals.css";
import Layout from "../components/layout";
import CreatContext from "./context/Context";
const geistMono = Roboto({
  weight: ["700"],
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Chinies habibi parts",
  description: "Generated by Habibi parts",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistMono.className} antialiased bg-b `}>
        <CreatContext>
          <Layout>{children}</Layout>
        </CreatContext>
      </body>
    </html>
  );
}
